version: "3.8"

services:

      backend: 
        build: .
        ports:
          - 8000:8000
        volumes:
          - .:/app/
        depends_on: 
          - db
        restart: always
        networks:
          - test

      db:
        image: "postgres"
        restart: always 
        environment:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'root'
          POSTGRES_DATABASE: 'my-postgres'
          POSTGRES_HOST: 'localhost'
          POSTGRES_PORT: '5432'
        networks:
          - test
  
networks:
  test: